//! Support items required by this crate's macros and by code generated by `assertr-macros`.
//!
//! Everything reachable from this module is a private implementation detail: it is
//! `#[doc(hidden)]`, exempt from semver guarantees, and must never be named directly. The macros
//! reach it through `$crate`, so no import is ever needed at a call site.

pub mod assert_that_macro;
pub(crate) mod field;
#[cfg(feature = "fluent")]
pub mod fluent_expressions;
pub(crate) mod partial_match;

use crate::assertions::core::pattern::Pattern;

/// Constructor behind [`pattern!`](crate::pattern).
///
/// [`Pattern`] has no public constructor: building one by hand would let the rendered pattern
/// source text and the predicate disagree, which the macro guarantees cannot happen.
#[must_use]
pub fn new_pattern<P>(description: &'static str, predicate: P) -> Pattern<P> {
    Pattern::new(description, predicate)
}

/// Empty tail of a macro-generated heterogeneous list.
pub struct Nil;
/// One element of a macro-generated heterogeneous list.
pub struct Cons<H, T>(pub H, pub T);

pub use field::field;
pub use partial_match::partial_match;

#[doc(hidden)]
pub use partial_match::PartialMatch;
