use crate::{
    AssertionContext, Expectation, ExpectationDiagnostics,
    expectation::{Evidence, MatcherList},
    failure::{FailureBuilder, FailureKind, PathSegment},
};
use core::marker::PhantomData;

/// A matcher generated by `partial!` for selected fields and enum variants.
/// Its representation is unsupported.
pub struct PartialMatch<A: ?Sized, P, L> {
    shape: P,
    fields: L,
    name: &'static str,
    variant: Option<&'static str>,
    actual: PhantomData<fn(&A)>,
}

#[doc(hidden)]
pub fn partial_match<A: ?Sized, P, L>(
    shape: P,
    fields: L,
    name: &'static str,
    variant: Option<&'static str>,
) -> PartialMatch<A, P, L>
where
    P: Fn(&A) -> bool,
{
    PartialMatch {
        shape,
        fields,
        name,
        variant,
        actual: PhantomData,
    }
}

impl<A: ?Sized, R, F, L> Expectation<A, R> for PartialMatch<A, F, L>
where
    F: Fn(&A) -> bool,
    L: MatcherList<A, R>,
{
    type Success<'a>
        = ()
    where
        Self: 'a,
        A: 'a;
    type Rejection<'a>
        = Evidence
    where
        Self: 'a,
        A: 'a;
    fn evaluate(&self, actual: &A, settings: &AssertionContext<'_, R>) -> Result<(), Evidence> {
        let mut context = settings.isolated();
        let evaluate = |context: &mut AssertionContext<'_, R>| {
            if !(self.shape)(actual) {
                return context.outcome(false, |_| {
                    FailureBuilder::detached::<()>(FailureKind::Matching)
                        .relation("has the required structure")
                        .expected(self.name)
                        .build()
                });
            }
            let mut matched = true;
            for index in 0..self.fields.len() {
                matched &= self.fields.evaluate_at(index, actual, context);
            }
            if !matched && context.evidence.is_empty() {
                context.outcome(matched, |_| {
                    FailureBuilder::detached::<()>(FailureKind::Matching)
                        .relation("has the required structure")
                        .expected(self.name)
                        .build()
                });
            }
            matched
        };
        let matched = if let Some(variant) = self.variant {
            context.scoped(PathSegment::Variant(variant), evaluate)
        } else {
            evaluate(&mut context)
        };
        let evidence = context.into_evidence();
        if matched { Ok(()) } else { Err(evidence) }
    }
}
impl<A: ?Sized, R, F, L> ExpectationDiagnostics<A, R> for PartialMatch<A, F, L>
where
    F: Fn(&A) -> bool,
    L: MatcherList<A, R>,
{
    const KIND: FailureKind = FailureKind::Matching;
    const FLATTEN: bool = true;
    fn explain<Target>(
        &self,
        rejected: Option<(&A, Evidence)>,
        failure: FailureBuilder<Target>,
        context: &AssertionContext<'_, R>,
    ) -> FailureBuilder<Target> {
        match rejected {
            None => context.describe_list::<A, _, _>(
                &self.fields,
                failure
                    .path(self.variant.map(PathSegment::Variant))
                    .relation("has the required structure")
                    .expected(self.name),
            ),
            Some((_, evidence)) => evidence.explain(failure.relation("does not match")),
        }
    }
}
#[cfg(test)]
mod tests {
    use super::partial_match;
    use crate::{
        expectation::predicate, failure::PathSegment, prelude::*, test_support::NoRenderer,
    };
    use core::cell::Cell;

    #[test]
    fn missing_subject_descriptions_preserve_nested_field_and_variant_paths() {
        use crate::{
            __private::field::field,
            assertions::{collection::elements_are_in_any_order, core::partial_eq::equal_to},
            failure::FailureKind,
        };
        let matcher = field(
            |row: &((i32,),)| Some(&row.0),
            partial_match(
                |_: &(i32,)| true,
                (field(
                    |row: &(i32,)| Some(&row.0),
                    equal_to(2),
                    PathSegment::TupleIndex(0),
                ),),
                "Choice::Some",
                Some("Some"),
            ),
            PathSegment::Field("choice"),
        );
        let actual: [((i32,),); 0] = [];
        let failures =
            assert_that!(actual).capture(|it| it.matches(elements_are_in_any_order((matcher,))));
        let description = failures[0].children[0].constraint.as_ref().unwrap();
        assert_that!(description.path)
            .is_equal_to([PathSegment::Field("choice"), PathSegment::Variant("Some")]);
        let field = &description.children[0];
        assert_that!(field.path).is_equal_to([PathSegment::TupleIndex(0)]);
        assert_that!(field.subject_type_name).is_equal_to("i32");
        assert_that!(field.kind).is_equal_to(FailureKind::Equality);
        assert_that!(field.relation.as_deref()).is_equal_to(Some("is equal to"));
    }

    #[test]
    #[cfg(feature = "matchers")]
    fn missing_partial_struct_descriptions_identify_each_selected_field() {
        struct Row {
            age: i32,
            score: i32,
        }
        let actual: [Row; 0] = [];
        let failures = assert_that!(actual).capture(|it| {
            it.matches(crate::elements_are_in_any_order![crate::partial!(Row {
                age: crate::matchers::eq(1),
                score: crate::matchers::eq(2)
            })])
        });
        let description = failures[0].children[0].constraint.as_ref().unwrap();
        assert_that!(description.children).has_length(2);
        for (child, name) in description.children.iter().zip(["age", "score"]) {
            assert_that!(child.path).is_equal_to([PathSegment::Field(name)]);
            assert_that!(child.kind).is_equal_to(crate::failure::FailureKind::Equality);
        }
    }

    #[test]
    fn wrong_shapes_skip_fields_and_retain_the_variant_path() {
        let calls = Cell::new(0);
        let matcher = partial_match(
            Option::is_some,
            (predicate(|_: &Option<i32>| {
                calls.set(calls.get() + 1);
                true
            }),),
            "Option::Some",
            Some("Some"),
        );
        let failures = assert_that!(None::<i32>)
            .with_renderer(NoRenderer)
            .capture(|it| it.matches(&matcher));

        assert_that!(calls.get()).is_equal_to(0);
        assert_that!(failures[0].children[0].path).is_equal_to([PathSegment::Variant("Some")]);

        assert_that!(Some(1))
            .with_renderer(NoRenderer)
            .matches(&matcher);
        assert_that!(calls.get()).is_equal_to(1);
    }
}
