[package]
name = "assertr-derive"
version = "0.3.0"
edition = "2024"
rust-version = "1.89.0"
autotests = false
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/lpotthast/assertr"
description = """
Derive AssertrEq implementations.
"""
categories = ["development-tools::testing", "no-std"]
keywords = ["assertions", "assert", "assert-that", "testing"]

[lib]
proc-macro = true

[dependencies]
darling = "0.24.0"
proc-macro-crate = "3.5.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["extra-traits", "visit"] }

[dev-dependencies]
assertr = { path = "../assertr", features = ["std", "derive", "fluent"] }
indoc = "2.0.5"
trybuild = { version = "1.0.103", features = ["diff"] }

[[test]]
name = "tests"
path = "tests/progress.rs"
