//! Support types for code generated by `assertr-derive`.
//!
//! Everything in this module is an implementation detail of the derive macros: it is
//! `#[doc(hidden)]`, exempt from semver guarantees, and must never be used directly.

use core::fmt::{Debug, Formatter};

use crate::{AssertionRenderer, DebugRenderer, Eq};

/// Renders a value through [`DebugRenderer`] via autoref specialization.
///
/// [`SpecializedDebugRender`] resolves to the impl on `Self` when `DebugRenderer` supports `T`;
/// otherwise method resolution falls back through autoref to the impl on `&Self`, which writes
/// `<unrendered>`. The decision is made where the generated code instantiates this type, so it
/// only works for types that are concrete at that location. Do not collapse the two impls: that
/// would force every field type to satisfy the bound and break non-`Debug` fields.
pub struct SpecializedDebug<'a, T: ?Sized> {
    pub value: &'a T,
    pub renderer: &'a DebugRenderer,
}

pub trait SpecializedDebugRender {
    fn render(self, f: &mut Formatter<'_>) -> core::fmt::Result;
}

impl<T: ?Sized> SpecializedDebugRender for SpecializedDebug<'_, T>
where
    DebugRenderer: AssertionRenderer<T>,
{
    fn render(self, f: &mut Formatter<'_>) -> core::fmt::Result {
        AssertionRenderer::<T>::fmt(self.renderer, self.value, f)
    }
}

impl<T: ?Sized> SpecializedDebugRender for &SpecializedDebug<'_, T> {
    fn render(self, f: &mut Formatter<'_>) -> core::fmt::Result {
        f.write_str("<unrendered>")
    }
}

/// Debug-renders an [`enum@Eq`] matcher field whose type names generics of the generated matcher.
///
/// Such fields cannot use the autoref specialization above (it never resolves for a generic
/// type), so this wrapper's `Debug` impl is conditional on `DebugRenderer` supporting `T`. The
/// generated matcher's `Debug` impl carries that bound per generic field, mirroring the bounds
/// `#[derive(Debug)]` would require.
pub struct RenderableEq<'a, T> {
    pub value: &'a Eq<T>,
    pub renderer: &'a DebugRenderer,
}

impl<T> Debug for RenderableEq<'_, T>
where
    DebugRenderer: AssertionRenderer<T>,
{
    fn fmt(&self, f: &mut Formatter<'_>) -> core::fmt::Result {
        match self.value {
            Eq::Any => f.write_str("Eq::Any"),
            Eq::Eq(value) => {
                f.write_str("Eq::Eq(")?;
                AssertionRenderer::<T>::fmt(self.renderer, value, f)?;
                f.write_str(")")
            }
        }
    }
}
