use super::{AssertrMatcher, ConstraintDescription, MatchContext, MatchResult, MatcherList};
use crate::failure::PathSegment;
use core::marker::PhantomData;

/// A matcher generated by `partial!` for selected fields and enum variants.
/// Its representation is unsupported.
pub struct PartialMatch<A: ?Sized, P, L> {
    shape: P,
    fields: L,
    name: &'static str,
    variant: Option<&'static str>,
    actual: PhantomData<fn(&A)>,
}

#[doc(hidden)]
pub fn partial_match<A: ?Sized, P, L>(
    shape: P,
    fields: L,
    name: &'static str,
    variant: Option<&'static str>,
) -> PartialMatch<A, P, L>
where
    P: Fn(&A) -> bool,
{
    PartialMatch {
        shape,
        fields,
        name,
        variant,
        actual: PhantomData,
    }
}

impl<A: ?Sized, P, L> PartialMatch<A, P, L>
where
    P: Fn(&A) -> bool,
{
    fn evaluate_structure<R>(&self, actual: &A, context: &mut MatchContext<'_, R>) -> MatchResult
    where
        L: MatcherList<A, R>,
    {
        if !(self.shape)(actual) {
            return context.outcome(false, |context| self.describe(context));
        }
        let mut group = context.isolated();
        let mut matched = true;
        for index in 0..self.fields.len() {
            matched &= self.fields.evaluate_at(index, actual, &mut group).matched;
        }
        if matched != context.is_positive() {
            if group.evidence.is_empty() && group.omitted == 0 {
                group.outcome(matched, |context| self.describe(context));
            }
            context.append(group);
        }
        MatchResult::new(matched)
    }
}

impl<A: ?Sized, R, P, L> AssertrMatcher<A, R> for PartialMatch<A, P, L>
where
    P: Fn(&A) -> bool,
    L: MatcherList<A, R>,
{
    fn describe(&self, context: &MatchContext<'_, R>) -> ConstraintDescription {
        ConstraintDescription::new("has the required structure")
            .expected(self.name)
            .omitted_children(
                self.fields
                    .len()
                    .saturating_sub(context.render().max_items()),
            )
            .children(
                (0..self.fields.len().min(context.render().max_items()))
                    .map(|index| self.fields.describe_at(index, context)),
            )
    }

    fn evaluate(&self, actual: &A, context: &mut MatchContext<'_, R>) -> MatchResult {
        if let Some(variant) = self.variant {
            context.scoped(PathSegment::Variant(variant), |context| {
                self.evaluate_structure(actual, context)
            })
        } else {
            self.evaluate_structure(actual, context)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::partial_match;
    use crate::{failure::PathSegment, matchers::predicate, prelude::*, test_support::NoRenderer};
    use core::cell::Cell;

    #[test]
    fn wrong_shapes_skip_fields_and_retain_the_variant_path() {
        let calls = Cell::new(0);
        let matcher = partial_match(
            Option::is_some,
            (predicate(|_: &Option<i32>| {
                calls.set(calls.get() + 1);
                true
            }),),
            "Option::Some",
            Some("Some"),
        );
        let failures = assert_that!(None::<i32>)
            .with_renderer(NoRenderer)
            .capture(|it| it.matches(&matcher));

        assert_that!(calls.get()).is_equal_to(0);
        assert_that!(failures[0].children[0].path).is_equal_to([PathSegment::Variant("Some")]);

        assert_that!(Some(1))
            .with_renderer(NoRenderer)
            .matches(&matcher);
        assert_that!(calls.get()).is_equal_to(1);
    }
}
